kgar/foundry-vtt-tidy-5e-sheets

- src/components/item-info-card/SpellbookItemCardContent.svelte
- src/components/item-list/controls/AttuneControl.svelte
- src/components/item-list/controls/EquipControl.svelte
- src/components/spellbook/SpellPrepareControl.svelte
- src/components/spellbook/SpellbookList.svelte
- src/sheets/actor/ListItemQuantity.svelte
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/vehicle/VehicleAttributesTab.svelte
Resolves spell deletion error and properly updates the spell list. #25
> [#25] Resolved Spell Deletion Error

- src/foundry/foundry-adapter.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/character/tabs/ActorJournalTab.svelte
- src/sheets/character/tabs/CharacterBiographyTab.svelte
- src/sheets/npc/tabs/NpcBiographyTab.svelte
- src/types/types.ts
Enriches Biography and Journal tabs for PCs and NPCs #27
> [#27] Enriched Biography and Journal tabs for PCs and NPCs

- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/sheets/character/parts/InventoryGrid.svelte
> Corrected URL issue.

- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/sheets/character/parts/InventoryGrid.svelte
> [#43] Fixed missing icon issue for dev server and prod build.

- src/sheets/item/LootSheet.svelte
- src/sheets/item/tabs/ItemLootDetailsTab.svelte
- src/sheets/itemSheetTabs.ts
> [#31] dnd5e 2.4.0 Compatibility - Loot Details Tab

- src/components/item-list/ItemUses.svelte
- src/components/spellbook/SpellbookList.svelte
#31
Miscellaneous updates based on remaining 2.4.0 PRs.
> [#31] dnd5e 2.4.0 Compatibility - Misc

- src/components/accordion/Accordion.svelte
- src/components/accordion/AccordionItem.svelte
- src/components/editor/OpenSheetEditor.svelte
- src/foundry/foundry-adapter.ts
- src/scss/partials/_items.scss
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/item/parts/ItemDescriptions.svelte
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
- src/theme/default-light-theme.ts
- src/types/item.ts
> [#31] dnd5e 2.4.0 Compatibility - Item Descriptions with Accordion

- src/sheets/item/parts/ItemDescriptions.svelte
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
Promoted editor to entire tab content area for item descriptions.
> [#31] One more thing

- src/scss/core.scss
- src/sheets/settings/theme/ThemeSettingsSheet.svelte
Restored Firefox scrollbars from original Tidy 5e.
> [#61] Fixed Formidable Firefox Scrollbars

- src/components/item-list/controls/ItemDeleteControl.svelte
- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
> [#73] Fixed Advancement Removal Dialog on Item Delete

- src/scss/core.scss
> [#78] Added style support for custom 5e enrichers

- src/components/item-list/ItemTableRow.svelte
> [#81] Hide item cards while dragging

- package-lock.json
- package.json
npm install sass@latest
npm install svelte-awesome-color-picker@latest
npm install svelte-check@latest
npm install svelte@latest
npm install terser@latest
npm update
> chore: Dependencies update

- src/scss/core.scss
> [#94] Monk's Little Details Compatibility

- src/sheets/item/tabs/ItemAdvancementTab.svelte
> [#106] Fixed Eldritch Horror SVG Error

- macros/transfer-alpha-tidy-data-to-original.js
- macros/transfer-original-tidy-data-to-alpha.js
- public/lang/en.json
- src/applications/sheet-settings/tabs/PlayerSettingsTab.svelte
- src/settings/settings.ts
- src/sheets/actor/SkillsList.svelte
- src/sheets/character/tabs/CharacterAttributesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
> [#91] Added "Toggle Empty Character Skills" setting, default false

- src/utils/formula.ts
> [#118] Corrected max prepared spell formula typo

- src/applications/sheet-settings/tabs/GmOptionsSettingsTab.svelte
- src/applications/sheet-settings/tabs/PlayerSettingsTab.svelte
> [#132] Moved world permission to GM Options

- src/sheets/character/parts/Rest.svelte
> [#134] Fixed issue with square portrait players not being able to rest

- src/components/inputs/TextInput.svelte
- src/sheets/actor/ListItemQuantity.svelte
> [#136] Changed Item Quantity number input to text with delta support

- public/lang/en.json
- src/sheets/character/parts/InventoryList.svelte
> [#137] Widened inventory weight column, added overflow control, adjusted localization

- public/lang/en.json
- src/context-menu/tidy5e-context-menu.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
> [#145] Misc style, wording, and formatting updates

- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/character/CharacterSheetFull.svelte
- src/sheets/npc/NpcSheetFull.svelte
- src/sheets/vehicle/VehicleSheetFull.svelte
- src/types/item.ts
- src/types/types.ts
> [#154] Fixed undefined banners

- src/components/item-list/ItemTableRow.svelte
> [#128] Updated item table descriptions to refresh when item descriptions change

- src/sheets/character/CharacterSheetFull.svelte
> [#157] Expanded max-width of XP tracker for player characters

- .github/workflows/refresh-documentation.yml
- package.json
- src/api/Tidy5eSheetsApi.ts
- src/api/index.ts
- src/api/tab/CustomTabBase.ts
- src/api/tab/HandlebarsTab.ts
- src/api/tab/HtmlTab.ts
- src/main.ts
- src/sheets/actor/SheetMenu.svelte
> [#112] Updated JsDoc and prepared for documentation generation via Github actions

- .github/workflows/refresh-documentation.yml
> [#112] Adjusted github action for auto-generating documentation on releases

- compatibility/world-scripts/midi-qol-action-list-reaction-remapping.js
- public/lang/en.json
- src/api/Tidy5eSheetsApi.ts
- src/api/action-list/ActionListApi.ts
- src/api/index.ts
- src/applications/sheet-settings/tabs/FeaturesSettingsTab.svelte
- src/features/actions/actions.ts
- src/runtime/action-list/ActionListRuntime.ts
- src/settings/settings.ts
> [#140] API: Implemented Action List Activation Type remapping

- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/foundry/foundry-adapter.ts
- src/main.ts
- src/settings/settings.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/character/parts/InventoryGrid.svelte
> [#54] Expanded extensibility for Item Macro integration

- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookList.svelte
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/sheets/character/parts/FavoriteFeaturesList.svelte
- src/sheets/character/parts/FavoriteSpellsList.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/vehicle/tabs/VehicleAttributesTab.svelte
- src/sheets/vehicle/tabs/VehicleCargoAndCrewTab.svelte
> [#176] Hotfix for items not rolling

- src/components/spellbook/SpellComponents.svelte
- src/scss/compatibility/_apps-items-lists.scss
- src/scss/core.scss
- src/scss/partials/_items.scss
- src/sheets/actor/TraitSection.svelte
- src/sheets/item/BackgroundSheet.svelte
- src/sheets/item/BackpackSheet.svelte
- src/sheets/item/ClassSheet.svelte
- src/sheets/item/ConsumableSheet.svelte
- src/sheets/item/EquipmentSheet.svelte
- src/sheets/item/FeatSheet.svelte
- src/sheets/item/LootSheet.svelte
- src/sheets/item/RaceSheet.svelte
- src/sheets/item/SpellSheet.svelte
- src/sheets/item/SubclassSheet.svelte
- src/sheets/item/ToolSheet.svelte
- src/sheets/item/WeaponSheet.svelte
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/item/tabs/ItemAdvancementTab.svelte
- src/sheets/item/tabs/ItemRaceDescriptionTab.svelte
> [#180] Resolved advancement tab edit issue and visual issues

- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/item/tabs/ItemAdvancementTab.svelte
> [#183] Added Drag/Drop for Item Active Effects and Item Advancements

- src/components/inputs/TextInput.svelte
- src/sheets/item/parts/ItemAction.svelte
> [#187] Fixed issue where setting Versatile formula causes damage formulae to be removed

- src/components/item-list/ItemTableRow.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/constants.ts
- src/sheets/character/parts/InventoryGrid.svelte
> [#192] api: Hooks for item hover ON/OFF

- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/api/exhaustion/ExhaustionApi.ts
- src/api/index.ts
> [#185] api: Exhaustion and Vehicle Exhaustion support

- src/context-menu/tidy5e-context-menu.ts
> [#151] Added compatibility for Item Piles and other context-menu-adding modules

- src/constants.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/utils/class-inheritance.ts
> [#198] Added support for PC inventory spell-to-scroll drops, vehicle spell-to-scroll and cargo drops

- compatibility/world-scripts/items-with-spells-5e.js
- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/api/index.ts
- src/api/tab/CustomTabBase.ts
- src/api/tab/HandlebarsTab.ts
- src/api/tab/HtmlTab.ts
- src/api/tab/SvelteTab.ts
- src/runtime/types.ts
- src/types/types.ts
> docs: Added `onRender` segment to tab examples

- src/components/accordion/AccordionItem.svelte
- src/sheets/item/parts/ItemDescriptions.svelte
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
> Issue 200 item description secrets

- src/sheets/Tidy5eItemSheet.ts
> [#213] Fixed item sheet issue with buttons disabling for observer users

- src/components/tabs/Tabs.svelte
- src/foundry/foundry-adapter.ts
> [#210] Actors and Items: added hooks for preSelectTab (with ability to prevent tab selection) and selectTab

- src/components/tabs/Tabs.svelte
> [#210] Added tab selection hooks calls to tab strip initialization

- src/scss/compatibility/_tabs.scss
> [#104] Added some compatibility styles for transplanted tabs to deal with scroll

- src/scss/compatibility/_tabs.scss
- src/scss/partials/_items.scss
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
> [#123] Added default sheet compatibility styles for Item Sheet HTML/classes

- src/scss/partials/_items.scss
- src/sheets/item/parts/ItemAction.svelte
> [#123] More compatibility styles

- src/scss/core.scss
- src/scss/partials/_actor.scss
- src/scss/partials/_items.scss
> [#80] Restored a more OG Tidy look to the roll buttons and editor line heights

- src/runtime/tab/TabManager.ts
> [#243] Prevents custom tab errors from keeping sheet from rendering

- src/api/Tidy5eSheetsApi.ts
- src/api/actor-portrait/ActorPortraitApi.ts
- src/api/api.types.ts
- src/api/index.ts
- src/runtime/ActorItemRuntime.ts
- src/runtime/ActorPortraitRuntime.ts
- src/runtime/CharacterSheetRuntime.ts
- src/runtime/types.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/ActorPortrait.svelte
- src/types/types.ts
> [#230] API/Hooks Support for Tokenizer

- public/lang/en.json
- src/components/spellbook/SpellbookFooter.svelte
- src/constants.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/types/types.ts
- src/utils/formula.ts
> [#234] Giving Spell Attack Bonus TLC

- src/sheets/Tidy5eKgarVehicleSheet.ts
> [#229] Fixed Consumable Item Drop on Vehicles

- src/sheets/actor/Currency.svelte
> [#235] Changed currency rendering for Compatibility with TheRipper's System Customizer 

- src/api/content/HtmlContent.ts
- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/constants.ts
- src/scss/partials/_actor.scss
- src/scss/partials/_items.scss
- src/scss/partials/_layout.scss
- src/scss/partials/_reset.scss
- src/sheets/CustomContentRenderer.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/AttributeBlock.svelte
- src/sheets/actor/DeathSaves.svelte
- src/sheets/actor/RollableBlockTitle.svelte
- src/sheets/actor/SkillsList.svelte
- src/sheets/actor/TraitSection.svelte
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/item/parts/ItemAction.svelte
- src/types/types.ts
> [#148] Ready Set Roll compatibility updates

- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/utils/applications.ts
> [#257] Preserve Named Input Focus (Custom Content) Between Non-Forced Re-rendering

- src/api/api.types.ts
- src/runtime/types.ts
- src/sheets/actor/ActorPortrait.svelte
> [#230] Expanded Portrait Menu Execution Params to include Actor Sheet Context

- src/utils/formula.ts
> [#261] Resolved spell DC tooltip error that seems to occur when Midi is enabled

- src/runtime/ActorPortraitRuntime.ts
> [#264] Fixed Portrait Menu Option errors

- src/utils/formula.ts
> [#266] Accounted for "None" spellcasting ability in the atk and dc tooltips.

- src/components/item-list/ItemCreateButton.svelte
- src/components/item-list/ItemTableRow.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/constants.ts
- src/sheets/character/parts/InventoryGrid.svelte
> [#263] Implemented Inventory/Spell Grid Drag-and-drop

- src/foundry/foundry-adapter.ts
- src/foundry/foundry-and-system.d.ts
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
> [#282] Updated Logic for Non-Actor Documents when Adding New Effect

- src/theme/default-dark-theme.ts
- src/theme/default-light-theme.ts
> [#276] Fixed: Missing Item Card Background and Missing Item Sheet Checkboxes for routePrefix servers

- src/applications/sheet-settings/tabs/InfoTab.svelte
- src/sheets/CustomContentRenderer.ts
- Corrected weblate URL in app.
- Added a guard clause to custom content rendering.
> Minor adjustments

- src/api/config/ConfigApi.ts
- src/api/config/action-list/ActionListApi.ts
- src/api/config/actor-item/ActorItemApi.ts
- src/api/config/actor-portrait/ActorPortraitApi.ts
- src/api/config/actor-traits/ActorTraitsApi.ts
- src/api/config/actor-traits/types.ts
- src/api/config/exhaustion/ExhaustionApi.ts
- src/api/config/item-summary/ItemSummaryApi.ts
- src/api/config/spell-school/SpellSchoolApi.ts
- src/components/item-list/ItemTableRow.svelte
- src/runtime/actor-traits/CustomActorTraitsRuntime.ts
- src/runtime/content/CustomContentManager.ts
- src/runtime/types.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/Traits.svelte
- src/types/types.ts
> [#158] Prepare for Arbron's Summoner Compatibility

- public/lang/en.json
- src/scss/core.scss
- src/settings/settings.ts
- src/theme/default-dark-theme.ts
- src/theme/default-light-theme.ts
- src/theme/theme-reference.ts
> [#302] Added theming for scrollbars

- src/components/expandable/ExpandableContainer.svelte
> [#321] Applied temporary fix for context menu being cut off in expandable sections

- public/lang/es.json
> Localization: Weblate Updates

- src/components/inputs/Select.svelte
- src/components/spellbook/SpellbookFooter.svelte
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/item/BackpackSheet.svelte
- src/sheets/item/ConsumableSheet.svelte
- src/sheets/item/EquipmentSheet.svelte
- src/sheets/item/LootSheet.svelte
- src/sheets/item/ToolSheet.svelte
- src/sheets/item/WeaponSheet.svelte
- src/types/types.ts
> [#331] [#211] Fixed Spellcasting ability None bug, rarity set to blank warning, and NPC prepared spells

- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/runtime/item/item-sheet-tabs.ts
- src/runtime/tab/TabManager.ts
- src/runtime/types.ts
- src/sheets/Tidy5eItemSheet.ts
- src/types/types.ts
> [#315] Item Details Tab Auto-Height and API support for custom tab auto-height

- public/lang/de.json
- public/lang/es.json
> Localization updates

- public/lang/cs.json
- public/lang/de.json
- public/lang/fr.json
- public/lang/hu.json
- public/lang/it.json
- public/lang/ja.json
- public/lang/ko.json
- public/lang/pl.json
- public/lang/zh-tw.json
Merged latest from Weblate translations.
> Weblate translations update

- src/sheets/vehicle/tabs/VehicleCargoAndCrewTab.svelte
> [#351] Fixes Cargo Column Edit Errors

- src/sheets/Tidy5eKgarVehicleSheet.ts
> [#352] Fixed Vehicle Drag and Drop Errors

- src/sheets/Tidy5eKgarVehicleSheet.ts
> [#353] Fixed Vehicle Sheet Description Tab Errors

- src/components/item-info-card/SpellbookItemCardContent.svelte
- src/components/item-list/controls/RechargeControl.svelte
- src/features/actions/actions.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/sheets/character/parts/FavoriteFeaturesList.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/vehicle/tabs/VehicleAttributesTab.svelte
> [#374] Fixed issue where bad item data kills the entire sheet

- src/scss/core.scss
> [#378] Fixed Property tag in item summaries to allow text wrapping

- src/sheets/character/tabs/CharacterBiographyTab.svelte
> [#384] Removed limits on Age and other bio fields

- src/main.ts
> [#387] Fixed Tidy error on initial load in Sheet Only module

- src/components/inputs/InlineTextDropdownList.svelte
- src/components/spellbook/SpellbookFooter.svelte
- src/foundry/foundry-adapter.ts
- src/sheets/actor/SkillsList.svelte
> [#367] Added Dropdown/Quick Change for a Skill's related ability when sheet is unlocked and editable

- public/lang/en.json
- src/components/filter/FilterToggleButton.svelte
- src/components/utility-bar/UtilityToolbar.svelte
- src/constants.ts
- src/runtime/item/ItemFilterRuntime.ts
- src/runtime/item/default-item-filters.ts
- src/runtime/item/item.types.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/SkillsList.svelte
- src/sheets/npc/parts/NpcLegendaryActions.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/types/types.ts
> [#390] NPC Abilities Tab Toolbar

- public/lang/en.json
- src/components/filter/FilterMenu.svelte
- src/constants.ts
- src/features/actions/actions.ts
- src/foundry/foundry-adapter.ts
- src/runtime/action-list/ActionListRuntime.ts
- src/runtime/item/ItemFilterRuntime.ts
- src/runtime/item/default-item-filters.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/types/types.ts
> [#401] [#404] Action List Tab Utility Toolbar and deterministic section sorting

- src/components/item-list/ItemTableRow.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/components/spellbook/SpellbookList.svelte
- src/foundry/foundry-adapter.ts
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/character/tabs/CharacterInventoryTab.svelte
- src/sheets/character/tabs/CharacterSpellbookTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/npc/tabs/NpcSpellbookTab.svelte
> [#413] Fixed: Clearing search causes injected content to not re-render

- src/sheets/vehicle/VehicleSheetFull.svelte
> [#423] Vehicle Type Selector on Vehicle Sheet Header

- src/components/content-concealment/ContentConcealer.svelte
- src/components/content-concealment/UnidentifiedNotice.svelte
- src/components/item-grid/GridPaneFavoriteIcon.svelte
- src/components/item-info-card/DefaultItemCardContentTemplate.svelte
- src/components/item-info-card/InventoryItemCardContent.svelte
- src/components/item-info-card/ItemInfoCard.svelte
- src/components/item-list/ItemName.svelte
- src/components/item-list/ItemSummary.svelte
- src/components/item-list/ItemUseButton.svelte
- src/foundry/foundry-adapter.ts
- src/scss/core.scss
- src/scss/partials/_items.scss
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/item/ConsumableSheet.svelte
- src/sheets/item/EquipmentSheet.svelte
- src/sheets/item/LootSheet.svelte
- src/sheets/item/ToolSheet.svelte
- src/sheets/item/WeaponSheet.svelte
- src/sheets/item/parts/ItemProfilePicture.svelte
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
- src/sheets/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/item/tabs/ItemLootDetailsTab.svelte
- src/sheets/item/tabs/ItemToolDetailsTab.svelte
- src/sheets/item/tabs/ItemWeaponDetailsTab.svelte
> [#355] Unidentified Items Concealment

- src/components/item-info-card/DefaultItemCardContentTemplate.svelte
- src/components/item-info-card/InventoryItemCardContent.svelte
- src/components/item-list/ItemSummary.svelte
- src/scss/core.scss
- src/scss/partials/_items.scss
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
- src/types/item.ts
> [#355] More Unidentified Item Refinements

- src/runtime/item/default-item-filters.ts
> [#432] "Prepared" Filter - Make it work for NPCs, too

- src/runtime/item/default-item-filters.ts
> [#432] (dnd5e 3.x) "Prepared" Filter - Make it work for NPCs, too

- src/api/api.types.ts
- src/api/config/ConfigApi.ts
- src/api/config/item/ItemConfigApi.ts
- src/runtime/item/ItemSheetRuntime.ts
- src/runtime/item/item.types.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/item/EquipmentSheet.svelte
- src/sheets/item/tabs/ItemEquipmentDetailsTab.svelte
- src/types/item.ts
> [#438] API: Custom Equipment Type Groups

- src/components/item-list/ItemTableRow.svelte
> [#441] Item Table Row Item Type Attribute

- src/scss/partials/_checkboxes.scss
- src/scss/partials/_items.scss
- src/theme/default-dark-theme.ts
> [#358] Green Checkbox TLC

- public/lang/en.json
- src/components/item-list/ItemName.svelte
- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/SpellbookList.svelte
- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/sheets/character/parts/FavoriteFeaturesList.svelte
- src/sheets/character/parts/FavoriteSpellsList.svelte
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/item/BackgroundSheet.svelte
- src/sheets/item/ClassSheet.svelte
- src/sheets/item/FeatSheet.svelte
- src/sheets/item/RaceSheet.svelte
- src/sheets/item/SpellSheet.svelte
- src/sheets/item/SubclassSheet.svelte
- src/sheets/item/parts/ItemIdentifiableName.svelte
- src/sheets/item/parts/ItemProfilePicture.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/vehicle/tabs/VehicleAttributesTab.svelte
- src/sheets/vehicle/tabs/VehicleCargoAndCrewTab.svelte
- src/types/item.ts
> [#434] Unidentified Items, Refinements

- src/components/expandable/ExpandableContainer.svelte
Upgraded the ExpandableContainer component to properly manage overflow as a part of the transition event lifecycle, ending in the correct overflow state, based on whether the container is expanded or collapsed.
> Quick Fix: Expand Animation for Items and Descriptions

- public/lang/en.json
- src/applications/settings/world-settings/WorldSettings.svelte
- src/applications/settings/world-settings/WorldSettings.types.ts
- src/applications/settings/world-settings/WorldSettingsFormApplication.ts
- src/applications/settings/world-settings/tabs/ItemWorldSettingsTab.svelte
- src/constants.ts
- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
- src/settings/settings.ts
- src/sheets/item/ConsumableSheet.svelte
- src/sheets/item/ContainerSheet.svelte
- src/sheets/item/EquipmentSheet.svelte
- src/sheets/item/LootSheet.svelte
- src/sheets/item/ToolSheet.svelte
- src/sheets/item/WeaponSheet.svelte
> [#472] Item Identification Permission

- src/components/item-info-card/InventoryItemCardContent.svelte
- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
- src/runtime/item/default-item-filters.ts
- src/sheets/character/parts/InventoryGrid.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/item/tabs/ItemContainerContentsTab.svelte
> [#471] Attunement and Rarity Concealment - Filters, Buttons, State Icons

- src/sheets/item/tabs/ItemContainerContentsTab.svelte
- src/sheets/shared/ContainerPanel.svelte
Added permission guard to container panel edit.
Ditto for container contents classic controls.
> Containers - Guard Container Panel Edit and Contents Classic Controls

- src/sheets/Tidy5eCharacterSheet.ts
> [#479] Container Panel Fix for Firefox

- public/lang/en.json
- src/components/filter/FilterMenu.svelte
- src/components/filter/FilterToggleButton.svelte
- src/components/filter/PinnedFilterToggle.svelte
- src/components/filter/PinnedFilterToggles.svelte
- src/components/filter/_filter.scss
- src/features/actions/actions.ts
- src/runtime/item/ItemFilterRuntime.ts
- src/runtime/item/default-item-filters.ts
- src/runtime/item/item.types.ts
- src/scss/core.scss
- src/scss/partials/_variables.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/character/tabs/CharacterInventoryTab.svelte
- src/sheets/character/tabs/CharacterSpellbookTab.svelte
- src/sheets/item/tabs/ItemContainerContentsTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/npc/tabs/NpcSpellbookTab.svelte
- src/types/types.ts
- src/utils/ItemUtils.ts
- src/utils/SpellUtils.ts
- src/utils/item.ts
- src/utils/spell.ts
> [#478] Default Pinned Filters on Utility Bar

- public/lang/cs.json
- public/lang/de.json
- public/lang/en.json
- public/lang/es.json
- public/lang/fr.json
- public/lang/hu.json
- public/lang/it.json
- public/lang/ja.json
- public/lang/ko.json
- public/lang/pl.json
- public/lang/pt-BR.json
- public/lang/zh-tw.json
- src/components/context-menu/FloatingContextMenu.svelte
- src/components/item-list/ItemFilterLayoutToggle.svelte
- src/constants.ts
- src/foundry/foundry-adapter.ts
- src/runtime/ActorPortraitRuntime.ts
- src/scss/partials/_items.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/ActorPortrait.svelte
- src/sheets/item/parts/ItemProfilePicture.svelte
- src/types/types.ts
> [#485] English Translation Capitalization Adjustments and Localization Fixes, Sheet Image Menu Update, Minor Visual Updates and Fixes

- src/scss/partials/_items.scss
- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
> [#402] Fix style: Expensive item values cut off

- src/foundry/foundry-adapter.ts
- src/sheets/actor/AmmoSelector.svelte
> [#490] Fixed: Ammo Switcher Not Switching to New Ammo Properly

- src/components/item-info-card/DefaultItemCardContentTemplate.svelte
- src/components/item-info-card/InventoryItemCardContent.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/shared/ContainerPanel.svelte
> [#495] Undefined Unidentified Item Names

- public/lang/ja.json
I have cleaned up the ja.json file to be used for future localization, while fixing some player-facing strings only.
> set up base japanese localization

- src/foundry/foundry-adapter.ts
- src/scss/partials/_layout.scss
- src/sheets/item/parts/ItemAction.svelte
> [#514] UI: Summoning Config

- src/sheets/actor/LevelUpDropdown.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/types/types.ts
> [#512] NPC Level Selector

- public/lang/en.json
- src/applications/settings/world-settings/WorldSettings.types.ts
- src/applications/settings/world-settings/WorldSettingsFormApplication.ts
- src/applications/settings/world-settings/tabs/ItemWorldSettingsTab.svelte
- src/settings/settings.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
> [#509] Better Spell Scrolls Native Tidy

- src/foundry/foundry-adapter.ts
> [#365] Fixed: Vehicle Add Equipment error

- src/context-menu/tidy5e-context-menu.ts
- src/scss/partials/_items.scss
- src/sheets/item/parts/ItemActivation.svelte
- src/sheets/item/tabs/ItemSpellDetailsTab.svelte
> [#531] cleanup: 3.1 Deprecation Warnings

- src/scss/partials/_items.scss
- src/sheets/item/ConsumableSheet.svelte
- src/sheets/item/EquipmentSheet.svelte
> [#336] style: Put Item Subtitle Statuses on their own line

- public/lang/en.json
- src/applications/migrations/migration-selection/MigrationSelectionApplication.ts
- src/applications/sheet-preferences/ApplyTidySheetPreferences.svelte
- src/applications/sheet-preferences/ApplyTidySheetPreferencesApplication.ts
- src/foundry/foundry-and-system.d.ts
- src/main.ts
- src/settings/settings.ts
> [#539] feat: Tidy Default Sheets config menu

- src/components/inputs/Checkbox.svelte
- src/components/item-list/ItemUseButton.svelte
- src/components/spellbook/ConcentrationOverlayIcon.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/components/spellbook/SpellbookList.svelte
- src/constants.ts
- src/foundry/foundry-adapter.ts
- src/runtime/item/ItemSheetRuntime.ts
- src/runtime/item/item-sheet-tabs.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/ActorEffectsTab.svelte
- src/sheets/character/parts/FavoriteSpellsList.svelte
- src/sheets/item/parts/ItemAction.svelte
- src/sheets/item/parts/ItemStartingEquipment.svelte
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/item/tabs/ItemAdvancementTab.svelte
- src/sheets/item/tabs/ItemBackgroundDetailsTab.svelte
- src/sheets/item/tabs/ItemClassDetailsTab.svelte
- src/sheets/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/item/tabs/ItemSpellDetailsTab.svelte
- src/sheets/item/tabs/ItemWeaponDetailsTab.svelte
- src/sheets/npc/parts/NpcHealthFormulaRoller.svelte
- src/sheets/npc/parts/NpcHitPoints.svelte
- src/sheets/npc/parts/NpcProfile.svelte
> [#544] feat: Add in Missing 3.0.x/3.1.x Content

- public/lang/es.json
Currently translated at 100.0% (489 of 489 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/es/
> i18n: Translated using Weblate (Spanish)

- src/scss/core.scss
> [#550] style: New Enrichers

- src/scss/partials/_items.scss
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
> [#554] fixed: Item Effects tab with Info Notifications Crashes

- src/components/spellbook/ConcentrationOverlayIcon.svelte
- src/scss/partials/_variables.scss
- src/sheets/actor/SpecialSaves.svelte
> [#553] style: Concentration style revisions / TLC

- src/scss/core.scss
- src/scss/partials/_items.scss
> [#563] Fixed: Item Editors Don't Hide the Editor Container in Source Edit Mode

- src/scss/partials/_items.scss
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
> [#554] Ported fix for issue #554 to 3.0.x.

- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/types/types.ts
> [#525] NPC subclass validation

- public/lang/en.json
- src/applications/settings/world-settings/WorldSettings.svelte
- src/applications/settings/world-settings/WorldSettings.types.ts
- src/applications/settings/world-settings/WorldSettingsFormApplication.ts
- src/applications/settings/world-settings/tabs/IconsWorldSettingsTab.svelte
- src/constants.ts
- src/features/spell-school/SpellSchool.ts
- src/settings/settings.ts
> [#586] Spell School Icon World Setting

- src/sheets/item/tabs/ItemDescriptionWithSidebarTab.svelte
> [#587] Cyrillic Currency Dropdown issue

- src/sheets/character/tabs/CharacterSpellbookTab.svelte
- src/sheets/npc/tabs/NpcSpellbookTab.svelte
> [#411] Spellbooks: Always Show Slotted Sections

- src/runtime/item/default-item-filters.ts
- src/utils/ItemUtils.ts
- src/utils/SpellUtils.ts
> [#561] Can Use Filter Upgrade

- public/lang/en.json
- src/applications/migrations/v3/CcssToTidyMigration.svelte
Added CCSS compendium migration.
> CCSS Compendia Migration

- public/lang/es.json
Currently translated at 100.0% (517 of 517 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/es/
> i18n: Latest from Weblate

- src/context-menu/tidy5e-context-menu.ts
> #631 Fixed: Sidebar Container Context Menu Delete Not Working

- src/components/item-list/controls/EffectFavoriteControl.svelte
- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
- src/sheets/character/tabs/CharacterEffectsTab.svelte
> [#634] Fixed: Effects from other sources causes sheet to break

- src/components/item-info-card/item-info-card.ts
- src/features/sections/CharacterSheetSections.ts
- src/features/sections/ContainerSheetSections.ts
- src/features/sections/Inventory.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- tests/helpers/inventory.ts
- tests/projects/main/sections/sections-core.spec.ts
- tests/projects/main/sections/sections-localization.spec.ts
> [#632] Support Custom Item dataModel entries in Tidy Sheet Inventory (Steinhardt's Trick Weapons, Tasha's Tattoos)

- src/sheets/item/ConsumableSheet.svelte
> #577 Fixed: Redundant itemStatus tag on consumable sheet header

- src/components/spellbook/SpellbookList.svelte
- src/sheets/character/parts/FavoriteFeaturesList.svelte
- src/sheets/character/parts/FavoriteSpellsList.svelte
- src/sheets/character/parts/InventoryList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/vehicle/parts/CargoList.svelte
- src/sheets/vehicle/parts/PassengerOrCrewList.svelte
- src/sheets/vehicle/tabs/VehicleAttributesTab.svelte
> #562 Fixed: Overlapping tooltip from item name on Item Card

- src/sheets/actor/InventoryList.svelte
> [#271] Additional refining of NPC Inventory

- src/sheets/Tidy5eNpcSheet.ts
> [#271] NPC Inventory - Spell Scroll on Spell drop to Inventory Tab

- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/actor/AmmoSelector.svelte
> [#658] fixed: Some containers won't open

- README.md
- public/module.json
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/character/parts/FavoriteFeaturesList.svelte
- src/sheets/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/vehicle/tabs/VehicleAttributesTab.svelte
- src/types/types.ts
> [#663] dnd5e 3.3.0 Compatibility

- src/context-menu/tidy5e-context-menu.ts
> [#669] Charge/Uncharge Context Menu Item

- public/lang/en.json
- src/applications/settings/world-settings/WorldSettings.types.ts
- src/applications/settings/world-settings/WorldSettingsFormApplication.ts
- src/applications/settings/world-settings/tabs/NpcWorldSettingsTab.svelte
- src/migrations/v1/og-settings-to-v1.ts
- src/settings/settings.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/npc/parts/NpcProfile.svelte
> [#673] NPC Rest Cleanup

- public/lang/en.json
- src/constants.ts
- src/foundry/TidyFlags.ts
- src/migrations/BulkMigrations.svelte
- src/migrations/MigrationTally.ts
- src/migrations/migration.types.ts
- src/migrations/notification/MigrationNotification.svelte
- src/migrations/v3/CcssToTidyMigration.svelte
- src/migrations/v4/FavoritesToSystemMigration.svelte
- src/migrations/v5/BondsIdealsFlawsToSystemMigration.svelte
- src/migrations/v5/bonds-ideals-flaws-to-system.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/npc/tabs/NpcBiographyTab.svelte
> [#670] NPC Bonds, Ideals, Flaws - to system schema, plus migration

- public/lang/en.json
- src/applications/settings/user-settings/UserSettings.types.ts
- src/applications/settings/user-settings/UserSettingsFormApplication.ts
- src/applications/settings/user-settings/tabs/PlayerSettingsTab.svelte
- src/components/spellbook/SpellbookClassFilter.svelte
- src/constants.ts
- src/foundry/TidyFlags.ts
- src/foundry/foundry-adapter.ts
- src/migrations/BulkMigrations.svelte
- src/migrations/notification/MigrationNotification.svelte
- src/migrations/v3/CcssToTidyMigration.svelte
- src/migrations/v5/SpellClassToSourceClassMigration.svelte
- src/migrations/v5/bonds-ideals-flaws-to-system.ts
- src/migrations/v5/parent-class-to-source-class.ts
- src/migrations/v5/spell-class-to-source-class.ts
- src/scss/partials/_items.scss
- src/settings/settings.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
- src/sheets/character/tabs/CharacterSpellbookTab.svelte
- src/sheets/item/tabs/ItemSpellDetailsTab.svelte
> [#671] Item: Parent Class to Source Class migration

- public/lang/en.json
- src/applications/spell-source-class-assignments/SpellSourceClassAssignments.svelte
- src/applications/spell-source-class-assignments/SpellSourceClassAssignmentsFormApplication.ts
- src/foundry/foundry-adapter.ts
- src/scss/core.scss
- src/sheets/character/tabs/CharacterSpellbookTab.svelte
- src/sheets/npc/tabs/NpcSpellbookTab.svelte
> [#681] Assign Spells to Source Class

- src/sheets/item/tabs/ItemFeatDetailsTab.svelte
> [#689] Fixed: Null enchantment prop breaks feature sheet

- src/sheets/item/tabs/ItemFeatDetailsTab.svelte
> [#689] hotfix backport for broken feature sheets due to null source.enchantment prop

- src/components/pips/Pips.svelte
- src/components/pips/pips.scss
- src/integration/integration.ts
- src/integration/modules/Drakkenheim/DrakkenheimContaminationTabClassic.scss
- src/integration/modules/Drakkenheim/DrakkenheimCore.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreConstants.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreContaminationTab.svelte
- src/scss/core.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
> [#504] compat: Dungeons of Drakkenheim Tidy integration

- src/integration/integration.ts
- src/integration/modules/Drakkenheim/DrakkenheimContaminationTab.scss
- src/integration/modules/Drakkenheim/DrakkenheimCore.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreConstants.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreContaminationTab.svelte
- src/integration/modules/Drakkenheim/Pips.svelte
- src/integration/modules/Drakkenheim/pips.scss
- src/utils/applications.ts
> [#504] compat: Tidy x Dungeons of Drakkenheim dnd5e 3.2.x

- src/sheets/actor/EncumbranceBar.svelte
> [#701] ui: Encumbrance Threshold Visualization

- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
There is no github issue, only victory.
> Mission Moto: Fix the Object of Objects error

- src/components/expandable/ExpandableContainer.svelte
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheet.ts
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/EncumbranceBar.svelte
Tested, detected, and fixed additional issues related to user-initiated rapid double-rendering.
Applied other fixes as discovered.
> Mission Moto, second pass

- src/utils/formula.ts
> [#655] Fixed: Evaluate error when simplifying formula

- src/components/item-list/ItemSummary.svelte
- src/components/item-list/v1/ItemTableRow.svelte
- src/components/item-list/v2/ItemTableRowV2.svelte
> [#189] fixed: Expanded Item Descriptions sometimes don't update when sorted or moved from their current position

- src/tooltips/AttunementSummaryTooltip.svelte
- src/tooltips/tooltips.scss
> [#98] chore: Refactor CSS for tooltip item image

- src/tooltips/AttunementSummaryTooltip.svelte
- src/tooltips/tooltips.scss
> [#98] Fix: Item names break to new line in bad way when longer than 320px

- src/sheets/item/tabs/ItemLootDetailsTab.svelte
> [#728] Enable selection of subtypes for loot items

- src/applications/spell-source-class-assignments/SpellSourceClassAssignmentsFormApplication.ts
> [#741] fixed: "Assign Spells to Classes" crash

- src/components/item-info-card/DefaultItemCardContentTemplate.svelte
- src/components/item-info-card/InventoryItemCardContent.svelte
- src/components/item-info-card/SpellbookItemCardContent.svelte
- src/scss/core.scss
- src/sheets/item/parts/ItemDescriptions.svelte
> [#745] fixed: Description text is not selectable

- public/lang/en.json
- src/constants.ts
- src/keybindings/keybind-init.ts
- src/main.ts
- src/sheets/actor/SheetEditModeToggle.svelte
- src/sheets/shared/SheetHeaderEditModeToggle.svelte
> [#749] Sheet Lock toggle keybind

- src/sheets/Tidy5eGroupSheetClassic.ts
- src/sheets/group/parts/GroupMemberListItem.svelte
- src/sheets/group/parts/GroupSkills.svelte
- src/tooltips/GroupSkillTooltip.svelte
- src/types/group.types.ts
> [#755] bug: Group Sheet Skills

- src/sheets/actor/LimitedHeader.svelte
From the community:
https://discord.com/channels/1167985253072257115/1284468102121132042/1284468102121132042
> fixed: Limited Sheet Portrait was showing at full image size

- src/sheets/item/parts/ItemMountable.svelte
> [#761] fixed: Vehicle Equipment Item Sheet Crashes

- public/lang/es.json
Currently translated at 100.0% (538 of 538 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/es/
> Translated using Weblate (Spanish)

- src/applications/max-prepared-spells-config/MaxPreparedSpellsConfigFormApplication.ts
- src/foundry/TidyFlags.ts
- src/sheets/item/tabs/ItemClassDetailsTab.svelte
Fixed a class sheet details tab error.
Fixed max prepared spells data pull.
> quick fixes

- src/components/editor/SheetEditorV2.scss
- src/components/editor/SheetEditorV2.svelte
- src/foundry/foundry-and-system.d.ts
- src/scss/partials/_reset-v2.scss
- src/sheets/Tidy5eItemSheet.ts
- src/sheets/actor/ActorEffectsTab.svelte
- src/sheets/character/tabs/CharacterEffectsTab.svelte
- src/sheets/group/tabs/GroupDescriptionTab.svelte
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/npc/tabs/NpcEffectsTab.svelte
- src/types/types.ts
- Group Sheet editor styles
- Truncation for effects tabs #740 
- Added support for Secret blocks in the new App V2 group sheet
- Added context menu for item effects
> Quick fix group sheet tlc

- src/sheets/Tidy5eItemSheetClassic.ts
- src/sheets/actor/ActorEffectsTab.svelte
- src/sheets/character/tabs/CharacterEffectsTab.svelte
- src/sheets/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/npc/tabs/NpcEffectsTab.svelte
- Added truncation and titles to active effects tabs
- Added Item Active Effect context menu
> [#740] Active Effect tab cell truncation and item active effects tab context menu support

- src/components/utility-bar/Search.svelte
- src/scss/partials/_actor.scss
> [#778] ui: Actor name and search bar height didn't scale with core pt size increase

- src/components/utility-bar/Search.svelte
- src/scss/partials/_actor.scss
- src/sheets/character/CharacterSheetFull.svelte
> [#778] UI fix for core pt size changes, in 3.3.x dnd5e

- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/main.ts
- src/mixins/SvelteApplicationMixin.ts
- src/runtime/header-controls/HeaderControlsRuntime.ts
- src/utils/DebugTools.ts
> [#792] Header Controls API

- public/lang/en.json
- src/foundry/foundry-adapter.ts
- src/integration/integration-classes.ts
- src/integration/integration.ts
- src/integration/modules/CustomCharacterSheetsModuleIntegration.ts
- src/integration/modules/Drakkenheim/DrakkenheimCore.ts
- src/integration/modules/PopoutModuleIntegration.ts
- src/integration/system/TidyCustomSectionsInDefaultItemSheetIntegration.ts
- src/main.ts
- src/sheets/actor/TempHp.svelte
> 4.0.x care package

- src/features/ready-hooks.ts
- src/main.ts
> [#738] Assign Spell to Source Class when Filtering by Class in Spellbook

- src/applications/spell-source-class-assignments/SpellSourceClassAssignments.svelte
- src/components/actor-link-indicator/ActorLinkIndicator.svelte
- src/components/toggle/ConditionToggle.svelte
- src/components/toggle/PropertyToggle.svelte
- src/components/toggle/TidySwitch.svelte
- src/components/toggle/_toggles.scss
- src/features/ready-hooks.ts
- src/main.ts
- src/scss/compatibility/_apps-items-lists.scss
- src/scss/partials/_items.scss
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/actor/SheetEditModeToggle.svelte
- src/sheets/character/parts/FavoriteEffectsList.svelte
- src/sheets/npc/NpcSheetFull.svelte
- src/sheets/shared/SheetHeaderEditModeToggle.svelte
> [#809] Tidy V5.10.0 feature port

- src/foundry/foundry-adapter.ts
- src/mixins/Tidy5eActorSheetBaseMixin.ts
- src/scss/partials/_reset-v2.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eContainerSheetClassic.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/item/tabs/ItemWeaponDetailsTab.svelte
- #828
- ArmorClassConfig dep warning resolved
- Fixed: Spell Scrolls were failing intermittently to create on spell drop to containers
- Minor CSS fixes
> Dnd5e 4.1.x compat 2nd pass

- src/components/spellbook/SpellbookList.svelte
- src/features/sections/SheetSections.ts
- src/mixins/SvelteApplicationMixin.ts
- src/sheets/item/parts/FieldUses.svelte
- src/types/types.ts
> [#842] Spellbook fixes

- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
- src/sheets/item/parts/ItemActivation.svelte
- src/utils/formula.ts
> [#838] fixes

- src/components/spellbook/SpellbookList.svelte
- src/sheets/actor/InventoryList.svelte
- src/sheets/character/parts/FavoriteSpellsList.svelte
Added inline activities for spells and favorite spells.
> quick fix: Inline Activities for Spell Lists

- src/components/item-list/InlineActivitiesList.svelte
- src/context-menu/tidy5e-context-menu.ts
- src/features/activities/activities.ts
- src/features/sections/CharacterSheetSections.ts
- src/scss/partials/_actor.scss
- src/scss/partials/_layout.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eItemSheetClassic.ts
- src/sheets/character/parts/FacilityOrderProgressMeter.svelte
- src/sheets/character/parts/FacilityOrderProgressTracker.svelte
- src/sheets/character/parts/FavoriteFacilities.svelte
- src/sheets/character/parts/Favorites.svelte
- src/sheets/item/tabs/ItemActivitiesTab.svelte
- src/tooltips/OccupantSummaryTooltip.svelte
- src/types/types.ts
> [#841] feat: Favorite Facilities

- public/lang/pl.json
Currently translated at 100.0% (517 of 517 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/pl/
> Translated using Weblate (Polish)

- src/scss/partials/_actor.scss
- src/sheets/character/parts/FavoriteActivitiesList.svelte
Increased min width of actor sheets to 750px.
> quick fix: Reduced width of item column in favorite activities list.

- src/sheets/item/tabs/ItemActivitiesTab.svelte
> [#862] fixed: Duplicating Secret buttons on Activity tab use click

- src/sheets/classic/item/tabs/ItemEquipmentDetailsTab.svelte
> [#879] armor magical bonus mapping fix

- src/components/toggle/ConditionToggle.svelte
- src/features/sections/SheetSections.ts
- fixed: Favorites section config like show/hide and sort were not being applied properly.
- fixed: Condition toggle styles were not changing properly when toggling a condition
> bug: Quick fixes 01 04 2025

- public/lang/cs.json
- public/lang/de.json
- public/lang/en.json
- public/lang/es.json
- public/lang/fr.json
- public/lang/it.json
- public/lang/ja.json
- public/lang/ko.json
- public/lang/pl.json
- public/lang/pt-BR.json
- public/lang/ta.json
- public/lang/uk.json
- src/applications/max-prepared-spells-config/MaxPreparedSpellsConfigFormApplication.svelte.ts
- src/components/spellbook/SpellbookFooter.svelte
- src/scss/classic/partials/_items.scss
- src/sheets/classic/item/parts/DetailsSpellcasting.svelte
> [#906] Spell Preparation Minor TLC

- src/components/item-list/item-table.scss
- src/components/spellbook/SpellbookList.svelte
> [#824] feat: Spell Cast Activity Item Linked Source Icon Tooltip on spellbook table entries

- src/components/item-list/InlineActivitiesList.svelte
- src/components/item-list/ItemSummary.svelte
- src/components/item-list/controls/RechargeControl.svelte
- src/components/item-list/v1/ItemTableRow.svelte
- src/components/item-list/v2/ItemTableRowV2.svelte
- src/components/spellbook/SpellbookList.svelte
- src/features/activities/activities.ts
- src/features/containers/Container.ts
- src/foundry/foundry-adapter.ts
- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/Tidy5eGroupSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eKgarVehicleSheet.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/actor/tabs/ActorActionsTab.svelte
- src/sheets/classic/character/parts/FavoriteFeaturesList.svelte
- src/sheets/classic/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/classic/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/classic/vehicle/tabs/VehicleAttributesTab.svelte
- src/types/item.types.ts
- src/types/types.ts
> [#899] feat: Activity Recharge / Charges UI

- src/sheets/classic/group/tabs/GroupInventoryTab.svelte
> quick fix: Locked + No Items, Group Sheet Currency Visibility

- src/sheets/classic/item/parts/FieldUses.svelte
> [#919] fixed: Destroy on Empty on showing when false

- public/lang/en.json
- src/foundry/foundry-adapter.ts
- src/scss/classic/partials/_actor.scss
- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/character/parts/FacilityOccupant.svelte
- src/sheets/classic/character/parts/FacilityRosterOccupant.svelte
- src/sheets/classic/character/tabs/CharacterBastionTab.svelte
- src/types/types.ts
> [#948] fix: Broken bastion tab when linked actor deleted from source location

- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
... and this bug has been sitting here for a 2-3 Tidy major versions, if I understand correctly ... 😬
> quick fix: Replaced outdated re-render code with a literal call to render().

- src/components/content-concealment/ContentConcealer.svelte
- src/components/content-concealment/UnidentifiedNotice.svelte
- src/components/item-list/ItemSummary.svelte
- src/features/expand-collapse/ExpansionTracker.svelte.ts
- src/scss/classic/classic-app-v1.scss
- src/scss/classic/classic-app-v2.scss
- src/sheets/classic/item/tabs/ItemDescriptionWithSidebarTab.svelte
> [#637] Unidentified styles adjustments and gobalizing, and quick fix for expansion tracker

- src/components/item-list/v1/ItemTableRow.svelte
- src/components/item-list/v2/ItemTableRowV2.svelte
- src/sheets/classic/mixins/BaseSheetCustomSectionMixin.ts
> [#942] fixed: Drag and Drop Manual Sorting Not Sorting Properly

- src/features/sections/CharacterSheetSections.ts
- src/foundry/config.types.ts
- src/sheets/classic/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/classic/item/tabs/ItemFeatDetailsTab.svelte
- src/types/types.ts
> [#725] Character Feature Tab - Active / Passive / Custom section - Feature Type Column

- src/components/item-list/ItemUses.svelte
- src/components/item-list/item-table.scss
- src/components/spellbook/SpellbookList.svelte
- src/components/table/tidy-table.scss
- src/features/activities/activities.ts
- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/character/parts/FavoriteSpellsList.svelte
- src/types/types.ts
#946 
Nothing major, just a little QoL while trying to figure out how many uses an additional spell has.
> [#946] feat: linked uses calculation added

- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/text.scss
- src/scss/quadrone/forms.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/scss/tidy5e.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/ItemDebugSheet.svelte
- Fixes and tweaks to core form, field, and input styles
- Table style updates
- Debug sheet content added
> Quadrone styles testing

- src/components/utility/TidyVisibilityObserver.svelte
- src/features/sections/SheetSections.ts
- src/sheets/quadrone/container/tabs/ContainerDetailsTab.svelte
- src/sheets/quadrone/item/parts/DetailsSpellcasting.svelte
- src/sheets/quadrone/item/parts/FieldDamage.svelte
- src/sheets/quadrone/item/parts/FieldUses.svelte
- src/sheets/quadrone/item/parts/ItemProperties.svelte
- src/sheets/quadrone/item/parts/ItemStartingEquipment.svelte
- src/sheets/quadrone/item/parts/SectionsFormGroup.svelte
- src/sheets/quadrone/item/tabs/ItemClassDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFacilityDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFeatDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemLootDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemSpellDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemToolDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemWeaponDetailsTab.svelte
- src/todo.md
- src/types/item.types.ts
Here I am, once again, working on the UI overhaul 💅
> UI overhaul third strike 4

- src/scss/quadrone/typography.scss
- src/scss/tidy5e.scss
- src/scss/util.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/ItemDebugSheet.svelte
- Added new typography helper classes
- Added spacing variables
- Removed broken .dark parent class from debug sheet
> Quadrone helper classes and spacing variables

- src/features/attribute-pins/AttributePins.ts
- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
> fixed: Compendium Actor Attribute Pins break sheet

- src/sheets/classic/actor/SkillsList.svelte
> #1005 Adjustments to Skill Ability dropdown and bugfix

- public/lang/uk.json
Currently translated at 100.0% (536 of 536 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/uk/
> Translated using Weblate (Ukrainian)

- src/components/buttons/PinnedFilterToggle.svelte
- src/runtime/item/default-item-filters.ts
- src/scss/quadrone/components/buttons.scss
- src/sheets/quadrone/container/tabs/ContainerContentsTab.svelte
Rest assured a new branch will rise in the place of this one.
> UI overhaul the legend continues again

- src/components/trackers/InlineItemQuantityTracker.svelte
- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/pills.scss
- src/scss/quadrone/components/toggles.scss
- src/scss/quadrone/components/trackers.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/item/ItemDebugSheet.svelte
- Header row sizing, border, positioning
- Rarity select style
- Action bar control styles
- Row control styles
- Header icon style fixes
> Container style fixes

- src/foundry/config.types.ts
- src/scss/quadrone/apps.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/items.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/SpellSheet.svelte
- src/sheets/quadrone/item/parts/Sidebar.svelte
- src/sheets/quadrone/item/parts/SpellBlock.svelte
- src/sheets/quadrone/item/parts/header/ItemLinkedItemSummary.svelte
- src/todo.md
- src/types/item.types.ts
Corrected dark spell prep mode colors. Corrected light pact color name.
Moved editor styles to the editor stylesheet part.
Added Prepared switch to spell sidebar.
> UI Overhaul - Road Warrior

- src/components/table-quadrone/TidyInlineActivitiesList.svelte
- src/scss/quadrone/tables.scss
- src/scss/util.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/item/tabs/ItemEffectsTab.svelte
Misc fixes for container polishing phase.
> UI overhaul 3 fes

- src/components/table-quadrone/TidyEffectSummary.svelte
- src/components/table-quadrone/TidyItemSummary.svelte
- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/parts/ContainerHeaderStart.svelte
- src/sheets/quadrone/item/parts/ItemHeaderStart.svelte
- src/sheets/quadrone/item/tabs/ItemEffectsTab.svelte
- Effects table styles (still need to update the missing image styling
- Description table styles
- Fixed minimized header styling
- Added some missing classes to Effects
- Started move off of .dark classes to .theme-dark
- Moved item description styles to editors file
> Quadrone styling v2

- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/container/tabs/ContainerDetailsTab.svelte
- src/sheets/quadrone/item/parts/FieldUses.svelte
- src/sheets/quadrone/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemEffectsTab.svelte
- src/sheets/quadrone/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemToolDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemWeaponDetailsTab.svelte
- Fixed row equipped, rarity, unidentified styles.
- Fixed bug with attunement checkbox labeling and formatting.
- Fixed item sheet backgrounds in dark mode.
**Other issues**
- Need `.unidentified` class added to rows, need to add unidentified styles.
> Container table cleanup

- src/components/info-card/Parts/ItemCardPills.svelte
- src/components/item-list/ItemSummary.svelte
- src/components/table-quadrone/TidyActivitySummary.svelte
- src/components/table-quadrone/TidyActivityTableRow.svelte
- src/components/table-quadrone/TidyItemSummary.svelte
- src/components/table-quadrone/TidyItemTableRow.svelte
- src/components/table-quadrone/TidyTableHeaderCell.svelte
- src/components/table-quadrone/TidyTableHeaderRow.svelte
- src/components/table-quadrone/TidyTableRow.svelte
- src/constants.ts
- src/context-menu/tidy5e-activities-context-menu.ts
- src/features/properties/ItemProperties.svelte.ts
- src/features/properties/properties.types.ts
- src/foundry/foundry-adapter.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/item/tabs/ItemActivitiesTab.svelte
- src/sheets/quadrone/item/tabs/ItemEffectsTab.svelte
- src/todo.md
- src/types/item.types.ts
🎶 A river in a dry land
The last ace in a lost hand
When the hope of new beginnings burned our feet
Now we need it
A heartbeat for a tin man
Oasis in a singed land
Remind us what we're here for
Creating new life
Creating rivers in the desert 🎶
#964
> UI Overhaul 5 Royal 🃏

- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/meters.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/forms.scss
- src/scss/quadrone/inventory.scss
- src/scss/quadrone/tables.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/container/ContainerSheet.svelte
- src/sheets/quadrone/container/parts/CapacityBar.svelte
- src/sheets/quadrone/container/parts/CapacityTracker.svelte
- src/sheets/quadrone/item/parts/DetailsSpellcasting.svelte
- src/sheets/quadrone/item/parts/FieldDamage.svelte
- src/sheets/quadrone/item/parts/FieldTargets.svelte
- src/sheets/quadrone/item/parts/FieldUses.svelte
- src/sheets/quadrone/item/parts/ItemProperties.svelte
- src/sheets/quadrone/item/parts/ItemStartingEquipment.svelte
- src/sheets/quadrone/item/parts/header/ItemChargesSummary.svelte
- src/sheets/quadrone/item/parts/header/ItemPriceSummary.svelte
- src/sheets/quadrone/item/parts/header/ItemRechargeSummary.svelte
- src/sheets/quadrone/item/parts/header/ItemWeightSummary.svelte
- src/sheets/quadrone/item/tabs/ItemClassDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFeatDetailsTab.svelte
- src/todo.md
- Header dropdown menu styles
- Fixed prosemirror styling
- Container footer style fixes
- All form fields now displaying as expected
- Fixed remaining checkbox alignment issues
- Started adding reusable label helper classes (needs to be added to cell contents in lieu of overrides)
- Other misc style fixes and tweaks around the sheet
> Container style cleanup for launch

- src/applications/section-selector/SectionSelector.svelte
- src/components/action-bar/FilterButtonMenuQuadrone.svelte
- src/components/action-bar/SortButtonWithMenuQuadrone.svelte
- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/pills.scss
- src/scss/quadrone/forms.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/shared/ExpandCollapseButton.svelte
- Action bar fixes after removing oninverse/ondefault styles
- Fixed pill `.lighter` styles
- Cleaned up section selection modal
> Style cleanup

- src/applications-quadrone/configure-sections/ConfigureSections.svelte
- src/applications/section-selector/SectionSelector.svelte
- src/components/action-bar/FilterButtonMenuQuadrone.svelte
- src/components/action-bar/SortButtonWithMenuQuadrone.svelte
- src/components/buttons/FilterToggle.svelte
- src/components/filter/FilterToggleButton.svelte
- src/components/filter/_filter.scss
- src/components/listbox/SortingListbox.svelte
- src/components/listbox/listbox.scss
- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/listboxes.scss
- src/scss/quadrone/dialogs.scss
- src/scss/quadrone/tables.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/container/ContainerSheet.svelte
- src/sheets/quadrone/container/tabs/ContainerContentsTab.svelte
- src/sheets/quadrone/item/ItemDebugSheet.svelte
- src/sheets/quadrone/item/parts/DetailsSpellcasting.svelte
- src/sheets/quadrone/item/parts/FieldUses.svelte
- src/sheets/quadrone/item/parts/ItemStartingEquipment.svelte
- src/sheets/quadrone/item/parts/Sidebar.svelte
- src/sheets/quadrone/item/tabs/ItemActivitiesTab.svelte
- src/sheets/quadrone/item/tabs/ItemEffectsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFacilityDetailsTab.svelte
- src/sheets/quadrone/shared/CollapsibleEditorSection.svelte
- src/sheets/quadrone/shared/ExpandCollapseButton.svelte
- Refactored button classes, applied broadly across the app (also forgot to commit mid-stream here 😅)
- Cleaned up modals to use new styles
- Added some missing headings and `title`s
- Fixed sidebar Section pill styling
- Fixed some radio button formatting
> Button refactor

- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
> [#1033] fixed: Item sheets randomly crashing

- src/components/listbox/Listbox.svelte
- src/scss/floating-context-menu.scss
- src/scss/quadrone/components/listboxes.scss
- src/scss/variables-quadrone.scss
- Restyled context menus for Quadrone
- Fixed sortable listbox focus style in light mode
> Final fixes for beta

- src/scss/quadrone/editors.scss
- src/scss/quadrone/tables.scss
Very minor light mode styling fixes for secret sections and empty containers
> Light mode launch bugs 🚨

- README.md
- src/context-menu/FloatingContextMenu.ts
- src/main.svelte.ts
- src/sheets/quadrone/item/parts/Sidebar.svelte
- src/utils/applications.svelte.ts
At long last, the first of many sheets to cross over to the new design!
> Tidy UI Overhaul Open Beta - Container Sheets

- src/context-menu/tidy5e-activities-context-menu.ts
- src/context-menu/tidy5e-group-context-menu.ts
- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
> fixes: Context Menu

- src/scss/quadrone/editors.scss
- src/scss/quadrone/forms.scss
- src/scss/quadrone/items.scss
- src/sheets/quadrone/container/parts/CapacityTracker.svelte
- src/sheets/quadrone/item/parts/header/ItemPriceSummary.svelte
- Container content cell styles
- Fieldset heading/legend spacing
- Container content footer now stays below content
- Bullet styles for dark mode now easier to read
> Minor CSS fixes

- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/npc/tabs/NpcAbilitiesTab.svelte
- src/types/types.ts
> [#1083] NPC Abilities Tab, Features Section, add Uses Column

- src/scss/quadrone/inventory.scss
- src/scss/quadrone/items.scss
- Container weight meter display
- Inline meter style
> Container meter style fixes!

- src/sheets/classic/item/parts/DetailsMountable.svelte
- src/sheets/classic/vehicle/tabs/VehicleAttributesTab.svelte
- src/sheets/quadrone/item/parts/DetailsMountable.svelte
> [#1087] fixed: Vehicle Attributes tab crashes with new items

- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/meters.scss
- src/scss/quadrone/components/pills.scss
- src/scss/quadrone/components/text.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/FacilitySheet.svelte
- src/sheets/quadrone/item/ItemDebugSheet.svelte
- New checks for static and disabled meter styles
- Bastion progress style fixes
- Checkbox alignment fix
> Start at facility sidebar fixes

- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/components/meters.scss
- src/scss/quadrone/editors.scss
- src/scss/variables-quadrone.scss
- Fixed HR styling (thanks Kharmans!)
- Fixed checkbox sizing discrepancies (thanks .application!)
> Description and checkbox tweaks

- src/scss/quadrone/apps.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/item/ClassSheet.svelte
- src/sheets/quadrone/item/tabs/ItemAdvancementTab.svelte
- Table row and header action styles updated!
- Added OG class indicator to class subtitle, updated styles across the board
- Stylized configured indicators on advancement section headers
> Table and class sheet style fixes for next beta

- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/inputs.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- Disabled checkbox styles
- Full height cells
- Fix for sidebar button oversight
- Header dropdown menu reads a little nicer
> Prep for next rogues

- src/integration/modules/DndTashasCauldron/ItemTattooDetailsQuadroneTab.svelte
- src/scss/quadrone/apps.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/forms.scss
- Borderless button style tweaks
- Tattoo details tab legend fix
- Tattoo details proficiency field lock
- Fix for rogue shadows in prosemirror
> Tattoos and more

- src/sheets/quadrone/item/parts/DetailsMountable.svelte
> quick fix: Vehicle Settings on Equipment Item Sheet

- src/components/editor/SheetEditorV2.scss
- src/sheets/classic/Tidy5eContainerSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eGroupSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/sheets/quadrone/Tidy5eContainerSheetQuadrone.svelte.ts
- src/sheets/quadrone/Tidy5eItemDebugSheetQuadrone.svelte.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
Changed sheets to use submitOnClose true, to better align with the default sheets.
> small feat: submitOnClose true for App V2 sheets

- package-lock.json
- package.json
- src/components/item-list/controls/ActionFilterOverrideControl.svelte
- src/components/item-list/controls/AttuneControl.svelte
- src/components/item-list/controls/EquipControl.svelte
- src/components/item-list/controls/ItemControl.svelte
- src/components/item-list/controls/ItemFavoriteControl.svelte
- src/components/spellbook/SpellPrepareControl.svelte
- src/components/spellbook/SpellbookList.svelte
- src/features/sections/SheetSections.ts
- src/mixins/TidyDocumentSheetMixin.svelte.ts
- src/sheets/classic/actor/InventoryList.svelte
- src/sheets/classic/actor/tabs/ActorActionsTab.svelte
- src/sheets/classic/character/tabs/CharacterFeaturesTab.svelte
- src/sheets/classic/item/tabs/ItemAdvancementTab.svelte
- src/sheets/classic/npc/tabs/NpcAbilitiesTab.svelte
- src/sheets/classic/vehicle/parts/CargoList.svelte
- src/sheets/classic/vehicle/tabs/VehicleAttributesTab.svelte
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/item/tabs/ItemActivitiesTab.svelte
- src/sheets/quadrone/item/tabs/ItemAdvancementTab.svelte
Fixes: 
https://discord.com/channels/1167985253072257115/1170003836556017755/1360601406486085872
#1130
https://discord.com/channels/1167985253072257115/1360670066265292951
https://discord.com/channels/1167985253072257115/1339488111125729301
> Quick Fixes Roundup

- svelte.config.js
> fixed: Random Reactivity Issues

- public/images/notable-left-corner.svg
- public/images/notable-right-corner.svg
- src/scss/quadrone/editors.scss
- Support for missing system styles (notable, quest, advice, narrative)
- Embedded statblock ability layout bug fix
> Editor style fixes

- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/character/parts/Rest.svelte
- src/sheets/classic/npc/parts/NpcRest.svelte
- src/sheets/quadrone/actor/CharacterSheet.svelte
- src/todo - 5.0.md
- src/types/types.ts
Fixed broken rest buttons.
Planned work.
> Quick fixes from testing

- public/lang/pt-BR.json
Currently translated at 100.0% (538 of 538 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/pt_BR/
> Translated using Weblate (Portuguese (Brazil))

- public/lang/en.json
- src/applications/settings/parts/ListboxSetting.svelte
- src/applications/tab-configuration/SheetTabConfigurationQuadrone.svelte
- src/applications/tab-configuration/parts/TabConfigurationEntry.svelte
- src/components/listbox/SelectionListbox.svelte
- src/components/listbox/SelectionListboxToolbar.svelte
- src/components/table-quadrone/TidyItemSummary.svelte
- src/components/table-quadrone/table-buttons/EffectToggleButton.svelte
- src/runtime/item/ItemFilterRuntime.svelte.ts
- src/runtime/item/default-item-filters.ts
- src/scss/quadrone/actors.scss
- src/scss/quadrone/apps.scss
- src/scss/quadrone/character.scss
- src/scss/quadrone/components/action-bar.scss
- src/scss/quadrone/components/buttons.scss
- src/scss/quadrone/components/listboxes.scss
- src/scss/quadrone/components/pips.scss
- src/scss/quadrone/inventory.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/actor/character-parts/InspirationBadge.svelte
- src/sheets/quadrone/actor/parts/SkillsCard.svelte
- src/sheets/quadrone/actor/tabs/CharacterBastionTab.svelte
- src/sheets/quadrone/shared/ActionBar.svelte
- src/todo.md
- Bastion responsive behavior
- Biography responsive behavior
- Action Bar responsive behavior updates
- Minor dark mode style fixes
- Stacked inspiration badge fixed
- Container observer view use controls fixed
- Tab selection modal styled (but sides need flipping)
> More styling cleanup and responsive updates

- src/sheets/classic/Tidy5eActorSheetClassicV2Base.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/npc/parts/NpcLoyaltyTracker.svelte
> [#1221] Fixed: NPC loyalty crashes sheet

- README.md
- public/lang/en.json
- src/scss/quadrone/actors.scss
- src/scss/quadrone/character-parts/favorites.scss
- src/scss/quadrone/character.scss
- src/scss/variables-quadrone.scss
- src/sheets/quadrone/actor/character-parts/traits/CharacterTraitClasses.svelte
- src/sheets/quadrone/actor/parts/ToolsCard.svelte
- src/sheets/quadrone/actor/tabs/ActorJournalTab.svelte
- src/sheets/quadrone/actor/tabs/SidebarTabFavorites.svelte
- src/sheets/quadrone/shared/ActionTables.svelte
- src/sheets/quadrone/shared/FeatureTables.svelte
- src/sheets/quadrone/shared/InventoryTables.svelte
- src/sheets/quadrone/shared/SpellTables.svelte
- src/todo.md
* Added readme attributions!
* You get an empty state, and you get an empty state!
* Removed old variable styles that were misbehaving
* Fixed sidebar scrolling behavior
> BEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES!!!

- src/components/table-quadrone/TidyItemTableRow.svelte
- src/constants.ts
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/item/columns/ActivityDamageFormulasColumn.svelte
- src/sheets/quadrone/item/columns/ItemDamageFormulasColumn.svelte
- src/todo.md
- src/tooltips/Tooltip.ts
- src/types/types.ts
The Damage Formula column is outrageously untidy. Can the Tidy Gang clean up this mess and save the day?
> Damage Formula Cleanup

- public/lang/cs.json
Currently translated at 98.7% (576 of 583 strings)
Translate-URL: https://hosted.weblate.org/projects/foundry-vtt-tidy-5e-sheets/ui-strings/cs/
> Translated using Weblate (Czech)

- src/sheets/quadrone/Tidy5eActorSheetQuadroneBase.svelte.ts
Added transformation target favorites, if any, to the favorites merging code when transforming a Quadrone actor.
> Feat: On transform, merge ALL favorites

- src/scss/quadrone/actors.scss
- src/scss/quadrone/apps.scss
- src/scss/quadrone/character-parts/favorites.scss
- src/scss/quadrone/character.scss
- src/scss/quadrone/npc.scss
- src/scss/quadrone/reset.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/actor/CharacterSheet.svelte
- src/sheets/quadrone/actor/NpcSheet.svelte
- src/sheets/quadrone/actor/character-parts/AbilityScore.svelte
- src/sheets/quadrone/actor/character-parts/AbilityScoreNPC.svelte
- src/sheets/quadrone/actor/character-parts/favorites/FavoriteItemSpell.svelte
- src/sheets/quadrone/actor/npc-parts/Legendaries.svelte
- src/sheets/quadrone/actor/npc-parts/NpcSubtitle.svelte
- src/sheets/quadrone/actor/parts/ActorHeaderStart.svelte
- src/sheets/quadrone/actor/tabs/NpcStatblockTab.svelte
Still todo:
* Legendaries in the statblock tab styling
* Class styling in sidebar (copy from PC sheet Traits tab)
* Display background/subclass/etc in Statblock tab
* Show alignment/species/size in sidebar in Edit Mode, subtitle only in Play Mode
* Figure out solution for HP > 999
Needs testing:
* Validate character sheet header styles are still working as expected
> Refactored NPC ability scores and header styling

- src/scss/quadrone/actors.scss
- src/scss/quadrone/character.scss
- src/scss/quadrone/npc.scss
- src/sheets/quadrone/actor/NpcSheet.svelte
- src/sheets/quadrone/actor/npc-parts/NpcSubtitle.svelte
- src/sheets/quadrone/actor/parts/SpellcastingNpcSummaryCard.svelte
- NPC header now uses new ability row component
- Header ability row styles now fixed and consistently styled with parts that don't shift on resize
- PC header no longer scrolls horizontally
- NPC subtitle always shows all components, handles 2 lines gracefully
- NPC subtitle now shows concentration button
> Updated NPC header and subtitle

- src/scss/quadrone/npc.scss
- src/sheets/quadrone/actor/npc-parts/NpcSubtitle.svelte
NPCs cannot edit XP. It's prepared data that doesn't have any data schema backing to it.
> quick fix: Removed XP edit UI and styles from NPCs.

- src/main.svelte.ts
Added fallback to relative Tidy-module-relative path URL, to support both full web URLs and relative URLs.
> Button Icons Fix

- src/scss/quadrone/actors.scss
- src/scss/quadrone/group.scss
- src/sheets/quadrone/actor/GroupSheet.svelte
- src/sheets/quadrone/actor/group-parts/GroupMember.svelte
- src/sheets/quadrone/actor/group-parts/group-tab-sidebar/GroupTabSidebar.svelte
- src/sheets/quadrone/actor/tabs/GroupMembersTab.svelte
- Refined some of the actor hover styles
- Added sidebar check for actor styles
- Light mode Group sheet style fixes
> Group sheets test

- src/runtime/tables/GroupMemberColumnRuntime.svelte.ts
- src/scss/quadrone/group.scss
- src/sheets/quadrone/actor/GroupSheet.svelte
- src/sheets/quadrone/actor/character-parts/InspirationBadge.svelte
- src/sheets/quadrone/actor/group-parts/GroupMemberNameColumn.svelte
- src/sheets/quadrone/actor/group-parts/GroupSubtitle.svelte
- src/sheets/quadrone/actor/group-parts/group-tab-sidebar/GroupSkillsCard.svelte
- src/sheets/quadrone/actor/tabs/GroupBastionsTab.svelte
- src/sheets/quadrone/actor/tabs/GroupDescriptionTab.svelte
- src/sheets/quadrone/actor/tabs/GroupInventoryTab.svelte
- src/sheets/quadrone/actor/tabs/GroupMembersTab.svelte
- src/sheets/quadrone/item/columns/GroupCharacterXpColumn.svelte
- Group sheet member styles finalized
- Sidebar/tab content independent scrolling
- Inventory tab layout cleanup
- Hooked up header actions
- Scaffolded out description tab
- Updated hover styles for members tab
> Group sheet styling round 2

- src/runtime/tables/GroupMemberColumnRuntime.svelte.ts
- src/runtime/tables/default-item-columns.ts
- src/scss/quadrone/actors.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/tables.scss
- src/scss/shared/dnd5e2-ports.scss
- src/sheets/quadrone/item/columns/GroupVehicleCrewColumn.svelte
- src/sheets/quadrone/item/columns/ItemTimeColumn.svelte
- Fixed biography editors background color in dark mode
- Updated time column width and text trimming behavior
- Restyled embedded statblocks, fixed broken 2014 rules styling, and removed overlaps in the quadrone editor styling.
> Biography, time column, and embedded statblock style fixes

- src/sheets/quadrone/actor/tabs/CharacterBiographyTab.svelte
- src/sheets/quadrone/actor/tabs/NpcBiographyTab.svelte
NPC and Character Bios were being hidden twice, once in a snippet and once with an if statement. This removes the outer one as the if statement seems to be enough
> fix: biography visibility

- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/runtime/ActorSheetQuadroneRuntime.svelte.ts
- src/runtime/item/ItemSheetQuadroneRuntime.svelte.ts
- New: Tabs that are registered to Item and Actor sheets through the API are now included by default.
> Tab Registration TLC
