- src/components/inputs/Checkbox.svelte
- src/sheets/item/parts/ItemActivation.svelte
- src/sheets/item/tabs/ItemConsumableDetailsTab.svelte
#31 
Removes auto-destroy checkbox from ItemConsumableDetailstab.
Adds ItemActivation checkboxes for
- system.uses.autoDestroy
- system.target.prompt
- system.uses.prompt
- system.consume.scale
Changes checkbox tooltip to simple title attribute.
> [#31] dnd5e 2.4.0 Compatibility - Item Activation prompt checkboxes

- src/sheets/item/parts/ItemActivation.svelte
#31 
Applied revisions to ItemActivation for uses value and max. They now only appear when system uses is set to a "per" value like Charges.
Changed blank option for limited use periods to None.
Corrected localization key for system.consume.amount.
> [#31] dnd5e 2.4.0 Compatibility - More Item Activation refinements

- src/sheets/shared/InlineCreatureType.svelte
#63 
Added placeholder text for all creature types when a type is not present.
> [#63] Fixed missing Creature Type for new NPCs

- src/components/item-list/ItemSummary.svelte
- src/components/item-list/ItemTableRowSummary.svelte
- src/settings/settings.ts
- src/sheets/actor/TraitSection.svelte
- src/sheets/vehicle/parts/VehicleAttributes.svelte
#67 
Removed the global directive from all transitions so that they properly remove when a parent element removes them. Having them use `|global` was causing them to animate while trying to be removed, resulting in them staying there.
Also removed unused component.
> [#67] Fixed "Move Traits" bug

- src/components/spellbook/SpellComponents.svelte
Replaced CSS that relied on abbreviations with a simple tag class that applies the style in a language-agnostic way.
> [#69] Fixes spell component tag issue when using languages with different abbreviations

- public/lang/cs.json
- public/lang/de.json
- public/lang/en.json
- public/lang/es.json
- public/lang/fr.json
- public/lang/hu.json
- public/lang/it.json
- public/lang/ja.json
- public/lang/ko.json
- public/lang/pt-BR.json
- public/lang/zh-tw.json
- src/applications/actor-origin-summary/ActorOriginSummaryConfigFormApplication.ts
- src/applications/sheet-settings/SheetSettings.svelte
- src/applications/sheet-settings/SheetSettings.types.ts
- src/applications/sheet-settings/SheetSettingsFormApplication.ts
- src/applications/sheet-settings/parts/ListboxSetting.svelte
- src/applications/sheet-settings/tabs/GmOptionsSettingsTab.svelte
- src/applications/sheet-settings/tabs/LockSettingsTab.svelte
- src/applications/sheet-settings/tabs/NpcSettingsTab.svelte
- src/applications/sheet-settings/tabs/PlayerSettingsTab.svelte
- src/applications/sheet-settings/tabs/VehicleSettingsTab.svelte
- src/applications/tab-selection/TabSelection.svelte
- src/applications/tab-selection/TabSelectionFormApplication.ts
- src/context-menu/tidy5e-context-menu.ts
- src/scss/partials/_application-shell.scss
- src/settings/settings.ts
- src/sheets/Tidy5eCharacterSheet.ts
- src/sheets/Tidy5eKgarVehicleSheet.ts
- src/sheets/Tidy5eNpcSheet.ts
> [#75] Added Default Sheet Tabs configs for PCs, NPCs, and Vehicles

- public/lang/en.json
- src/actions/actions.ts
- src/applications/sheet-settings/SheetSettingsFormApplication.ts
- src/applications/sheet-settings/tabs/FeaturesSettingsTab.svelte
- src/settings/settings.ts
- src/sheets/actor/tabs/ActorActionsTab.svelte
#82 
Adds optional cantrip scaling to the damage column (default: On).
Resolves some minor issues.
> [#82] Actions Tab refinements, round 1

- community/max-prepared-spells-formulas.md
- public/lang/en.json
- src/applications/actor-origin-summary/ActorOriginSummaryConfigFormApplication.ts
- src/applications/max-prepared-spells-config/MaxPreparedSpellsConfig.svelte
- src/applications/max-prepared-spells-config/MaxPreparedSpellsConfigFormApplication.ts
- src/components/spellbook/SpellbookFooter.svelte
- src/scss/core.scss
- src/sheets/Tidy5eCharacterSheet.ts
- src/types/types.ts
- src/utils/formula.ts
> [#20] Max Prepared Spells upgrade

- src/components/item-list/ItemTableRow.svelte
- src/scss/partials/_actor.scss
- src/scss/partials/_items.scss
#143 
(Also, did some misc perf work on expanded item chat data refresh; unexpanded, hydrated chat data will clear on a change detection cycle now, so that they fetch fresh info on next open)
> [#143] Updated editors' editable area to span the full height of their containers

- src/foundry/foundry-adapter.ts
Was getting an undefined error when rolling NPC death saves on dnd5e 3.0. Fixed it with a quick bit of optional chaining.
> Fix for NPC death saves

- src/foundry/foundry-adapter.ts
> [#574] fixed: empty class identifier not falling back to slugified class name

- public/lang/en.json
- src/applications/migrations/v3/CcssToTidyMigration.svelte
CCSS and Tidy are now coordinating so that CCSS works with other sheets while Tidy does its own thing. For this reason, the migration wording needed to be updated to remove verbiage about CCSS taking precedence.
> CCSS Migration wording update

- src/utils/formula.ts
This is a stop-gap fix that addresses the most likely failure modes.
Bug: kgar/foundry-vtt-tidy-5e-sheets#667
> Partly fix a bug in calculateDeterministicBonus()

- src/sheets/actor/SkillsList.svelte
- src/utils/logging.ts
Adds optional args to all logging functions.
Adds guard code to prevent custom skills that are in CONFIG.DND5E.skills but not on the actor from crashing the resident sheet tab. Adds warning log advising of the missing skill.
> maintenance: Prevent missing skills from crashing resident tab

- src/utils/applications.ts
#504 
Fixed: When the user color scheme is set to `default` and the default theme is `dark`, it makes some text unreadable on the Contamination tab for the Dungeons of Drakkenheim integration.
> [#504] fix: Dark/Light Mode styles issue

- src/foundry/TidyFlags.ts
Fixed: when Max Prepared Spells is a number, an error was throwing when trying to trim the value.
> maintenance: Max Prepared Spells bugfix

- src/api/config/exhaustion/ExhaustionApi.ts
Updated exhaustion API so that preexisting hints are preserved if no new hints are provided by the API caller.
> maintenance: Exhaustion API updates

- src/context-menu/tidy5e-context-menu.ts
- src/foundry/foundry-adapter.ts
- src/runtime/item/default-item-filters.ts
- src/sheets/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/item/tabs/ItemContainerDetailsTab.svelte
- src/sheets/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/item/tabs/ItemToolDetailsTab.svelte
- src/sheets/item/tabs/ItemWeaponDetailsTab.svelte
Updated attunement eligibility logic to specifically check the configured attunementTypes, rather than just looking for a truthy value.
> fixed: Nonstandard attunement values on items mistakenly mark item as attune-able

- src/scss/partials/_items.scss
Isolated the combinator-based margin-top rule for form groups in item sheets so that it could be expanded to account for handlebars-based injected content.
> quick fix: Injected form-groups on item sheet, handling their spacing

- src/components/toggle/_toggles.scss
- src/sheets/actor/SheetEditModeToggle.svelte
Increased darkness of thumb icon on switch toggles.
Increased the switch scale to 1, to make it more satisfyingly centered and accessible.
> ui: last-minute Sheet Lock fine-tuning

- src/scss/partials/_items.scss
- src/sheets/container/ContainerContentsSections.svelte
- src/sheets/mixins/BaseSheetCustomSectionMixin.ts
> [#845] Container TLC

- src/scss/core.scss
> [#857] fix: Public Font Paths in Tidy disagree with route prefixing

- src/components/tabs/Tabs.svelte
Minor adjustment to prevent tidy item sheets from erroring on render when a module like Item Piles constructs a preview item that has no database backing.
> fix: Item Piles item preview compatibility

- src/features/actions/actions.svelte.ts
Fixed an issue where simplifying formulas evaluates to NaN. When this occurs, default to unaltered formula.
> quick fix: NaN on action tab damage column

- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/types/item.types.ts
Made itemSubtypes `undefined` by default so that the subtype template logic works properly.
> quick fix: Undefined Item Subtype

- src/components/editor/SheetEditorV2.svelte
- src/foundry/foundry-and-system.d.ts
Added the necessary code to fix this in Foundry V13. It won't work in V12 because I am using the `prose-mirror` HTML element.
> future fixed: the sheet editor magic wand button is missing

- src/scss/quadrone/apps.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/container/parts/ContainerContentsSections.svelte
- src/sheets/quadrone/container/parts/InlineContainerView.svelte
First pass at inline container style fixes.
Todos
1) In apps.scss move background images like denim out of the ::before. There's some kind of background blur applied to the container that I can't figure out how to turn off. Container sheet denim image moved to a working location for now.
2) Add `.expanded` class on a tidy table row if it's been expanded to either show description or container contents. 
3) For inline nested containers, remove the `.dark` class from the nested table header rows
4) I removed the filigree for now. It likely needs to be added to the container contents in the DOM hierarchy, but I didn't want to mess it up for now. Might rethink it anyhow
> Added inline container table styles

- src/scss/quadrone/forms.scss
- src/sheets/classic/item/tabs/ItemSpellDetailsTab.svelte
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
- src/sheets/quadrone/container/tabs/ContainerDetailsTab.svelte
- src/sheets/quadrone/item/parts/DetailsMountable.svelte
- src/sheets/quadrone/item/parts/DetailsSpellcasting.svelte
- src/sheets/quadrone/item/parts/FieldActivation.svelte
- src/sheets/quadrone/item/parts/FieldDamage.svelte
- src/sheets/quadrone/item/parts/FieldDuration.svelte
- src/sheets/quadrone/item/parts/FieldRange.svelte
- src/sheets/quadrone/item/parts/FieldTargets.svelte
- src/sheets/quadrone/item/parts/FieldUses.svelte
- src/sheets/quadrone/item/parts/ItemStartingEquipment.svelte
- src/sheets/quadrone/item/tabs/ItemBackgroundDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemClassDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemConsumableDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemEquipmentDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFacilityDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemFeatDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemLootDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemSpeciesDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemSpellDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemSubclassDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemToolDetailsTab.svelte
- src/sheets/quadrone/item/tabs/ItemWeaponDetailsTab.svelte
Fixed spell ability form fields in classic/q spell details tab.
Fixed: Properties were not showing the final state when locked. 
Corrected swap logic for context.source to account for sheet Mode.
Removed all usages of disabledValue, now that it is being supplied innately from source.
Added missing form field wrappers where found in Spell Sheet.
> Misc updates

- src/theme/theme.ts
fixed: Quadrone Sheets were perpetually in the dark mode (or whatever is the default computer theme preference).
> UI Overhaul The Dark Knight

- src/components/table-quadrone/TidyActivityTableRow.svelte
Moved data-configurable adjacent to data-activity-id to allow for activity configurability filtering with the context menu. Without it paired up, all standard options were being filtered out, as the activity was considered unconfigurable.
> quick fix: Activity Context Menu not showing options

- src/components/item-list/v1/EffectTableRow.svelte
- src/components/item-list/v1/ItemTableRow.svelte
- src/components/item-list/v2/ItemTableRowV2.svelte
- src/components/spellbook/SpellbookGrid.svelte
- src/components/table-quadrone/TidyActivityTableRow.svelte
- src/components/table-quadrone/TidyAdvancementTableRow.svelte
- src/components/table-quadrone/TidyEffectTableRow.svelte
- src/components/table-quadrone/TidyItemTableRow.svelte
- src/mixins/DragAndDropBaseMixin.ts
- src/scss/quadrone/tables.scss
- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/Tidy5eContainerSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eGroupSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/sheets/classic/Tidy5eKgarVehicleSheet.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
- src/sheets/classic/actor/InventoryGrid.svelte
- src/sheets/classic/item/tabs/ItemActiveEffectsTab.svelte
- src/sheets/classic/item/tabs/ItemActivitiesTab.svelte
- src/sheets/classic/item/tabs/ItemAdvancementTab.svelte
- src/sheets/classic/shared/ContainerPanel.svelte
- src/sheets/quadrone/Tidy5eCharacterSheetQuadrone.svelte.ts
- src/sheets/quadrone/Tidy5eContainerSheetQuadrone.svelte.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
- src/todo.md
Reviewed and refined the drag/drop setup. For now, added data-tidy-always-draggable attribute for those things that are always draggable, no matter the circumstances.
Fixed a bug where activities won't get properly added when their ID matches an activity ID on the trigger, instead triggering a sort.
Removed a rogue border on item images in the tidy table row use button.
> Drag and drop refinements of the current setup

- src/mixins/TidyDocumentSheetMixin.svelte.ts
Added try/catch to the close function in the App V2 doc sheet mixin when attempting to submit on close. The error will still log to the console, but the sheet will successfully close.
> quick fix: try/catch when submitting on close

- src/sheets/classic/Tidy5eItemSheetClassic.svelte.ts
- src/sheets/quadrone/Tidy5eItemSheetQuadrone.svelte.ts
- src/sheets/quadrone/item/tabs/ItemActivitiesTab.svelte
- fixed: Quadrone Activities tab header was not using title font and didn't have a count
- fixed: Drag/drop to sort on item sheets was creating a copy of the activity when embedded on an actor.
> Quick fixes 2025 04 27

- src/sheets/classic/Tidy5eCharacterSheet.svelte.ts
- src/sheets/classic/Tidy5eKgarVehicleSheet.svelte.ts
- src/sheets/classic/Tidy5eNpcSheet.svelte.ts
Made dragdrop bind on app v1 sheets more defensive. Some modules may cause `this.form` to be unavailable, apparently.
> [#1148] TypeError fix on App V1 sheets

- src/scss/quadrone/components/buttons.scss
- src/sheets/quadrone/shared/InventoryTables.svelte
Made Empty State for inventory sections only appear for root sections.
> UI overhaul last minute prep

- src/components/action-bar/FilterButtonMenuQuadrone.svelte
- src/components/filter/FilterButton.svelte
- src/components/tabs/UnderlinedTabStrip.svelte
- src/sheets/quadrone/shared/ActionBar.svelte
- Fixed: When two spell schools were translated as the same text, it would cause the Spellbook tab to crash.
> Quick fix translation issues

- src/runtime/tables/ItemColumnRuntime.svelte.ts
Added loot and consumable column priorities to creature and container inventory column loadouts.
Adjusted priority for loot and consumable columns to match their most common use case.
> Feat: loot / consumable column loadout and priority updates

- public/lang/en.json
- src/applications/theme/ThemeSettingColorFormGroupQuadrone.svelte
- src/applications/theme/ThemeSettingsQuadrone.svelte
- src/applications/theme/ThemeSettingsQuadroneApplication.svelte.ts
- src/runtime/tab/TabManager.ts
- src/sheets/quadrone/item/parts/ItemHeaderStart.svelte
- src/theme/theme-quadrone.svelte.ts
- src/theme/theme-quadrone.types.ts
- src/todo.md
- Fixed: When changing portrait shape in World Theme Settings, it would not apply to actors.
- New: For sheet theme configuration, any world theme settings will show up as input placeholders.
- Fixed: Item Sheet tab item counts went missing.
> UI overhaul maintenance 1 2025 08 01

- src/integration/integration.ts
- src/integration/modules/Drakkenheim/DrakkenheimCore.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreConstants.ts
- src/integration/modules/Drakkenheim/DrakkenheimCoreContaminationTab.svelte
- src/integration/modules/Drakkenheim/SebastianCrowesGuideToDrakkenheim.ts
Upgrade Drakkenheim to dual compatibility between Sebastian Crowe's Guide to Drakkenheim and Dungeons of Drakkenheim.
> compat: Double drakkenheims

- src/applications-quadrone/configure-sections/ConfigureSections.svelte
- src/scss/quadrone/actors.scss
- src/scss/quadrone/character-parts/favorites.scss
- src/scss/quadrone/forms.scss
- src/scss/quadrone/npc.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/actor/NpcSheet.svelte
- src/sheets/quadrone/actor/npc-parts/Legendaries.svelte
- src/sheets/quadrone/actor/npc-parts/NpcScoreTrackerCard.svelte
- src/sheets/quadrone/actor/tabs/NpcStatblockTab.svelte
- src/sheets/quadrone/item/parts/ItemStartingEquipment.svelte
- src/sheets/quadrone/item/tabs/ItemFeatDetailsTab.svelte
- src/todo.md
- Fixed some small alignment NPC header issues from fields/buttons
- NPC max HP field and overrides styled
- Inline cards for legendary actions styled up and prepped to hold...other item types 👀
- Transparent image background fixes for Letlev's issue; now properly only adds gold background for SVGs
- Fixed some form behavior to better handle lists of checkboxes/radios
- Fixed form fields to do a more greedy grab of mouse actions
I think we're down to just the additional sidebar/subtitle fields listed in the todos! Styles are all feeling solid
> NPC inline legendary styles, and header finalized

- src/components/info-card/Cards/SpellItemCard.svelte
- src/components/table-quadrone/TidyItemTableRow.svelte
- src/components/table-quadrone/table-buttons/SpellButton.svelte
- src/foundry/foundry-adapter.ts
- src/runtime/item/default-item-sorts.ts
- src/sheets/quadrone/item/parts/Sidebar.svelte
- src/sheets/quadrone/item/tabs/ItemSpellDetailsTab.svelte
- src/theme/theme.ts
- src/utils/SpellUtils.ts
Fixed: When a spell's method is undefined, the spellbook crashes. It is now updated to default to innate, as the system intends.
Fixed: Can Cast filter was still treating Pact spells as always castable instead of checking their preparedness.
> Quick fixes

- src/foundry/foundry-adapter.ts
- src/mixins/Tidy5eActorSheetBaseMixin.ts
- src/sheets/classic/Tidy5eActorSheetClassicV2Base.svelte.ts
- src/sheets/quadrone/Tidy5eActorSheetQuadroneBase.svelte.ts
- src/sheets/quadrone/Tidy5eCharacterSheetQuadrone.svelte.ts
- src/sheets/quadrone/Tidy5eNpcSheetQuadrone.svelte.ts
- src/sheets/quadrone/actor/character-parts/traits/CharacterTraits.svelte
- src/sheets/quadrone/actor/npc-parts/LoyaltyTracker.svelte
- src/sheets/quadrone/actor/npc-parts/NpcScoreTrackerCard.svelte
- src/sheets/quadrone/actor/npc-parts/NpcSubtitle.svelte
- src/sheets/quadrone/actor/npc-parts/NpcTraits.svelte
- src/sheets/quadrone/actor/parts/ActorTraitBackground.svelte
- src/sheets/quadrone/actor/parts/ActorTraitClasses.svelte
- src/sheets/quadrone/actor/parts/ActorTraitSize.svelte
- src/sheets/quadrone/actor/parts/ActorTraitSpecies.svelte
- src/sheets/quadrone/actor/tabs/NpcBiographyTab.svelte
- src/sheets/quadrone/actor/tabs/NpcStatblockTab.svelte
- src/todo.md
- src/types/types.ts
NPC todos:
Planned work for some additional missing items.
Generalized several components and context preparation functions so that NPCs and Characters can share.
Corrected Singleton warning loc key, as it has changed.
Added Creature Type to subtitle.
> UI Overhaul and the Return of Pickled Pete

- src/sheets/quadrone/actor/character-parts/traits/CharacterTraits.svelte
- src/sheets/quadrone/actor/npc-parts/NpcTraits.svelte
- src/sheets/quadrone/actor/parts/ActorTraitConfigurableListEntry.svelte
Updated ActorTraitConfigurableListEntry to allow specifying the desired position of the config button. Updated PCs to put the button at the end, and NPCs within the label.
> Quick fix: Config button location on traits entries

- src/theme/theme.ts
Fixed bug where the prescribed application color scheme was not being read properly and was defaulting to `prefers-color-scheme` inappropriately.
> quick fix - core theme bug

- .gitignore
- src/components/table-quadrone/TidyItemTableRow.svelte
- src/components/table-quadrone/table-buttons/EffectToggleButton.svelte
- src/scss/quadrone/actors.scss
- src/scss/quadrone/apps.scss
- src/scss/quadrone/character.scss
- src/scss/quadrone/components/meters.scss
- src/scss/quadrone/items.scss
- src/scss/quadrone/npc.scss
- src/scss/quadrone/tables.scss
- src/sheets/quadrone/Tidy5eNpcSheetQuadrone.svelte.ts
- src/sheets/quadrone/actor/CharacterSheet.svelte
- src/sheets/quadrone/actor/npc-parts/Legendaries.svelte
- src/sheets/quadrone/actor/npc-parts/LoyaltyTracker.svelte
- src/sheets/quadrone/actor/npc-parts/NpcSubtitle.svelte
- src/sheets/quadrone/actor/npc-parts/NpcTraits.svelte
- src/sheets/quadrone/actor/npc-parts/traits/NpcTraitCreatureType.svelte
- src/sheets/quadrone/actor/npc-parts/traits/NpcTraitSize.svelte
- src/sheets/quadrone/actor/parts/ActorTraitSize.svelte
- src/sheets/quadrone/actor/tabs/NpcStatblockTab.svelte
- src/sheets/quadrone/shared/EffectsTables.svelte
- src/sheets/quadrone/shared/InventoryTables.svelte
- src/sheets/quadrone/shared/ItemRollButton.svelte
- src/sheets/quadrone/shared/SpellTable.svelte
- src/todo.md
- Updated todos, still need to look at light mode sidebar trait label colors
- Reorganized Character Traits and NPC Traits to have a clearer distinction between the sidebar and Statblock tabs
- Updated Size to use a dropdown on the gear icon to better fit in to sidebar
- Migrated grey/unidentified/unprepared to use a common `.diminished` class
- Fixed collapsed ability styles on NPC and Character sheets
- Small fix to damage bypass colors in dark mode
> NPC sheet trait style fixes

- src/mixins/TidyDocumentSheetMixin.svelte.ts
- src/sheets/quadrone/container/parts/InlineContainerView.svelte
- Fixed: Inline container items and sections were not sorting based on the tab's sort option.
- Fixed: Container item drops were sometimes being ignored.
> quick fixes: Inline container sorting and container drop logic

- src/sheets/quadrone/actor/tabs/ActorSpellbookTab.svelte
Corrected spell pip prop path to be actor-specific and not hardcoded to Character 🤦‍♂️
> fixed: NPC Value/Max / Pips preferences (or quick tato fix)

- src/integration/modules/PopoutModuleIntegration.ts
- src/theme/theme-quadrone.svelte.ts
Theming now works on popped out sheets. They're kept in sync as the theme changes (currently only possible with global settings changes as the context menu at the top breaks in popout view, this is a popout problem as it breaks in vanilla dnd5e sheets too)
fix #1342
> fix[#1342]: popout now works with theming

- src/foundry/foundry-adapter.ts
- src/scss/quadrone/actors.scss
- src/scss/quadrone/components/meters.scss
- src/scss/quadrone/dialogs.scss
- src/scss/quadrone/group.scss
- src/scss/quadrone/tooltips.scss
- src/sheets/quadrone/actor/group-parts/GroupMemberNameColumn.svelte
- src/sheets/quadrone/actor/group-parts/GroupSubtitle.svelte
- src/sheets/quadrone/actor/tabs/GroupInventoryTab.svelte
- src/tooltips/GroupLanguageTooltip.svelte
- src/tooltips/GroupSkillTooltip.svelte
- src/tooltips/GroupToolTooltip.svelte
- src/tooltips/GroupTraitTooltip.svelte
- Styled group sidebar tooltips with updated headers, labels, proficiency, and top trait styles
- Updated group Skill proficiency icons to match Quadrone styles
- Fixed inventory tab scrolling behavior to properly sit flush with the sheet
- Fixed some actor subtitle styling in Group sheets
- Fixed Group sheet inventory footer layout
- Updated Group sheet header to hide speeds = 0
> Group sheet refinement

- package-lock.json
- src/scss/quadrone/character-parts/favorites.scss
- src/sheets/quadrone/actor/character-parts/favorites/FavoriteSkillTool.svelte
- src/sheets/quadrone/actor/character-parts/favorites/parts/FavoriteRollButton.svelte
I attempted to use follow this solution https://bugzilla.mozilla.org/show_bug.cgi?id=568313#c23 but it appears it only works if the button itself is draggable, instead, I've gone with the `role="button"` route.
fixes #1325 
Tested on Mac: Chromium (Vivaldi) and Firefox. Doesn't work on Safari, although that's parity with original
> fix[#1325]: replace favorite buttons with role="button"

- src/sheets/quadrone/Tidy5eGroupSheetQuadrone.svelte.ts
- src/types/types.ts
- Fixed: Skill High/Low not showing the total mod + bonus value. #1379
> Group sheet fixes roundup

- src/api/Tidy5eSheetsApi.ts
- src/api/api.types.ts
- src/integration/integration.ts
- src/integration/modules/McdmClassBundle/McdmClassBundle.ts
- src/integration/modules/McdmClassBundle/McdmClassBundleConstants.ts
- src/integration/modules/McdmClassBundle/McdmPowerDetailsTab.svelte
- src/integration/modules/McdmClassBundle/McdmPowerSheet.svelte
- src/integration/modules/McdmClassBundle/McdmPowerSpecialtyColumn.svelte
- src/integration/modules/McdmClassBundle/McdmPowersTab.scss
- src/integration/modules/McdmClassBundle/McdmPowersTab.svelte
- src/integration/modules/McdmClassBundle/McdmPowersTables.svelte
- src/runtime/item/TabDocumentItemTypesRuntime.ts
- src/sheets/quadrone/Tidy5eActorSheetQuadroneBase.svelte.ts
- src/sheets/quadrone/actor/character-parts/favorites/FavoriteItemGeneric.svelte
Things added/changed:
- Added: API function for registering document types which are valid for creation on a given tab
- Added: MCDM Class Bundle integration (Quadrone only)
- Powers tab for Characters and NPCs
- Both have tables of powers
- Characters get Strain table
- Power item sheet
- Changed: `FavoriteItemGeneric` had a minor glow-up (same "save" treatment as favorited spells)
> MCDM Class Bundle first pass

- src/main.svelte.ts
- src/mixins/TidyDocumentSheetMixin.svelte.ts
- src/runtime/tables/GroupMemberColumnRuntime.svelte.ts
- src/runtime/tables/default-item-columns.ts
- src/scss/quadrone/actors.scss
- src/scss/quadrone/editors.scss
- src/scss/quadrone/tables.scss
- src/scss/shared/dnd5e2-ports.scss
- src/sheets/quadrone/Tidy5eActorSheetQuadroneBase.svelte.ts
- src/sheets/quadrone/Tidy5eNpcSheetQuadrone.svelte.ts
- src/sheets/quadrone/actor/GroupSheet.svelte
- src/sheets/quadrone/actor/parts/ActorPortrait.svelte
- src/sheets/quadrone/item/columns/GroupVehicleCrewColumn.svelte
- src/sheets/quadrone/item/columns/ItemTimeColumn.svelte
- src/theme/theme-quadrone-detached.ts
- src/types/types.ts
- Ensured Foundry theme colors carry over to Foundry V14 Detached Windows. Addresses part of #1400 
- Fixed: Group sheet short rest button was not working.
- New: When rolling NPC HP, if the HP value is equal to the HP max, then HP value is now updated to match the new HP max.
- Fixed: When using Vehicle sheet crew labels like "30 crew / 40 passengers", the Group sheet crew column was strange. Thank you hightouch!
- Fixed: 2014-style statblock embeds had some layout issues. Thank you hightouch!
- Fixed: Time column was not handling longer text like Legendary Action very well. Thank you hightouch!
- Various style adjustments that make the sheets feel nice. Thank you hightouch!
- Fixed: Actor portrait paths could not be changed when the actor had wildcard tokens configured. Addresses #1401
> Misc updates and fixes
